### ISSUE TITLE
gson找不到parseString方法

### ISSUE THREAD

**Issue by ghost** [cloopen/java-sms-sdk#3]
导入容联·云通讯 Java SMS SDKv1.0.1
运行报错
NoSuchMethodError: com.google.gson.JsonParser.parseString
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
	at com.cloopen.rest.sdk.CCPRestSmsSDK.generateJson(CCPRestSmsSDK.java:289)
	at com.cloopen.rest.sdk.CCPRestSmsSDK.sendTemplateSMS(CCPRestSmsSDK.java:128)
	at xxx.xxx.util.SendMsg.sendSMS(SendMsg.java:83)
	at xxx.xxx.util.SendMsg.main(SendMsg.java:104)
```

**Comment by ghost** [comment]
## 已找到原因,在官方指导下了解到这个是由于 maven 版本依赖原则引起。
我的项目SpringBoot的parent约定的gson版本为2.8.0，而parent中的gson优先级高于java-sms-sdk v1.0.1的pom.xml，导致依赖jar版本不一致出问题

+ 我的项目 partent
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.1.RELEASE</version>
	</parent>
```

+ 解决方法
在java-sms-sdk前面引入gson 2.8.6
```
<dependency>
   <groupId>com.google.code.gson</groupId>
   <artifactId>gson</artifactId>
   <version>2.8.6</version>
</dependency>

<dependency>
   <groupId>com.cloopen</groupId>
   <artifactId>java-sms-sdk</artifactId>
   <version>1.0.1</version>
</dependency>
```
